spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eshghishop?createDatabaseIfNotExist=true
    username: root
    password: rootpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true